/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/car/car.gltf -t -r ./public 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
interface GLTFAction extends THREE.AnimationClip {
  name: string;
}
type GLTFResult = GLTF & {
  nodes: {
    Mesh002: THREE.Mesh;
    Mesh002_1: THREE.Mesh;
    Mesh002_2: THREE.Mesh;
    Circle004: THREE.Mesh;
    Circle004_1: THREE.Mesh;
    Circle004_2: THREE.Mesh;
    Mesh001: THREE.Mesh;
    Mesh001_1: THREE.Mesh;
    Mesh001_2: THREE.Mesh;
    Circle006: THREE.Mesh;
    Circle006_1: THREE.Mesh;
    Circle006_2: THREE.Mesh;
    Mesh003: THREE.Mesh;
    Mesh003_1: THREE.Mesh;
    Mesh003_2: THREE.Mesh;
    Circle007: THREE.Mesh;
    Circle007_1: THREE.Mesh;
    Circle007_2: THREE.Mesh;
    Mesh004: THREE.Mesh;
    Mesh004_1: THREE.Mesh;
    Mesh004_2: THREE.Mesh;
    Circle008: THREE.Mesh;
    Circle008_1: THREE.Mesh;
    Circle008_2: THREE.Mesh;
    Cube: THREE.Mesh;
    Cube_1: THREE.Mesh;
    Cube_2: THREE.Mesh;
    Cube_3: THREE.Mesh;
    Cube_4: THREE.Mesh;
    Cube_5: THREE.Mesh;
    Cube_6: THREE.Mesh;
    Cube_7: THREE.Mesh;
    Cube_8: THREE.Mesh;
    Cube_9: THREE.Mesh;
    Cube_10: THREE.Mesh;
    Cube_11: THREE.Mesh;
    Circle001_1: THREE.Mesh;
    Circle001_2: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube002_1: THREE.Mesh;
    Cube005: THREE.Mesh;
    Cube005_1: THREE.Mesh;
    Cube008: THREE.Mesh;
    Cube010_1: THREE.Mesh;
    Cube010_2: THREE.Mesh;
    Cube010_3: THREE.Mesh;
    Cube011_1: THREE.Mesh;
    Cube011_2: THREE.Mesh;
    Cube014: THREE.Mesh;
    Cube014_1: THREE.Mesh;
    Cube013: THREE.Mesh;
    Cube013_1: THREE.Mesh;
  };
  materials: {
    BrakeDisk_Mat: THREE.MeshStandardMaterial;
    bumper: THREE.MeshStandardMaterial;
    BrakeDisk_Mat1: THREE.MeshStandardMaterial;
    tyre: THREE.MeshStandardMaterial;
    ["Material.018"]: THREE.MeshStandardMaterial;
    ["Material.017"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshPhysicalMaterial;
    ["Material.013"]: THREE.MeshStandardMaterial;
    ["image (5)"]: THREE.MeshPhysicalMaterial;
    ["Material.016"]: THREE.MeshStandardMaterial;
    ["Material.021"]: THREE.MeshStandardMaterial;
    nevera: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Material.012"]: THREE.MeshPhysicalMaterial;
    ["Material.015"]: THREE.MeshStandardMaterial;
    glass: THREE.MeshPhysicalMaterial;
    ["Material.011"]: THREE.MeshStandardMaterial;
    ["Material.007"]: THREE.MeshStandardMaterial;
    ["Material.009"]: THREE.MeshPhysicalMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
    headlamp: THREE.MeshStandardMaterial;
    ["Material.008"]: THREE.MeshStandardMaterial;
    smallhedlamp: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Car(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/car/car.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.521, 0.372, 1.427]}
        rotation={[-0.785, -0.085, -3.085]}
      >
        <mesh
          geometry={nodes.Mesh002.geometry}
          material={materials.BrakeDisk_Mat}
        />
        <mesh geometry={nodes.Mesh002_1.geometry} material={materials.bumper} />
        <mesh
          geometry={nodes.Mesh002_2.geometry}
          material={materials.BrakeDisk_Mat1}
        />
      </group>
      <group
        position={[0.332, 0.378, 1.418]}
        rotation={[3.139, -0.013, -1.571]}
      >
        <mesh geometry={nodes.Circle004.geometry} material={materials.tyre} />
        <mesh
          geometry={nodes.Circle004_1.geometry}
          material={materials["Material.018"]}
        />
        <mesh
          geometry={nodes.Circle004_2.geometry}
          material={materials["Material.017"]}
        />
      </group>
      <group
        position={[-1.459, 0.372, 1.424]}
        rotation={[-2.321, 0.121, 0.112]}
      >
        <mesh
          geometry={nodes.Mesh001.geometry}
          material={materials.BrakeDisk_Mat}
        />
        <mesh geometry={nodes.Mesh001_1.geometry} material={materials.bumper} />
        <mesh
          geometry={nodes.Mesh001_2.geometry}
          material={materials.BrakeDisk_Mat1}
        />
      </group>
      <group position={[-1.27, 0.378, 1.415]} rotation={[0.002, 0.013, 1.571]}>
        <mesh geometry={nodes.Circle006.geometry} material={materials.tyre} />
        <mesh
          geometry={nodes.Circle006_1.geometry}
          material={materials["Material.018"]}
        />
        <mesh
          geometry={nodes.Circle006_2.geometry}
          material={materials["Material.017"]}
        />
      </group>
      <group position={[0.521, 0.376, -1.517]} rotation={[1.933, 0.246, 3.026]}>
        <mesh
          geometry={nodes.Mesh003.geometry}
          material={materials.BrakeDisk_Mat}
        />
        <mesh geometry={nodes.Mesh003_1.geometry} material={materials.bumper} />
        <mesh
          geometry={nodes.Mesh003_2.geometry}
          material={materials.BrakeDisk_Mat1}
        />
      </group>
      <group
        position={[0.326, 0.378, -1.514]}
        rotation={[-0.002, -0.013, -1.571]}
      >
        <mesh geometry={nodes.Circle007.geometry} material={materials.tyre} />
        <mesh
          geometry={nodes.Circle007_1.geometry}
          material={materials["Material.018"]}
        />
        <mesh
          geometry={nodes.Circle007_2.geometry}
          material={materials["Material.017"]}
        />
      </group>
      <group
        position={[-1.434, 0.376, -1.51]}
        rotation={[-2.271, -0.012, 0.015]}
      >
        <mesh
          geometry={nodes.Mesh004.geometry}
          material={materials.BrakeDisk_Mat}
        />
        <mesh geometry={nodes.Mesh004_1.geometry} material={materials.bumper} />
        <mesh
          geometry={nodes.Mesh004_2.geometry}
          material={materials.BrakeDisk_Mat1}
        />
      </group>
      <group
        position={[-1.243, 0.378, -1.514]}
        rotation={[0.002, 0.013, 1.571]}
      >
        <mesh geometry={nodes.Circle008.geometry} material={materials.tyre} />
        <mesh
          geometry={nodes.Circle008_1.geometry}
          material={materials["Material.018"]}
        />
        <mesh
          geometry={nodes.Circle008_2.geometry}
          material={materials["Material.017"]}
        />
      </group>
      <group position={[-0.464, 0.692, -0.287]} rotation={[-0.003, 0, 0]}>
        <mesh
          geometry={nodes.Cube.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Cube_1.geometry}
          material={materials["Material.013"]}
        />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.bumper} />
        <mesh
          geometry={nodes.Cube_3.geometry}
          material={materials["image (5)"]}
        />
        <mesh
          geometry={nodes.Cube_4.geometry}
          material={materials["Material.016"]}
        />
        <mesh
          geometry={nodes.Cube_5.geometry}
          material={materials["Material.021"]}
        />
        <mesh geometry={nodes.Cube_6.geometry} material={materials.nevera} />
        <mesh
          geometry={nodes.Cube_7.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Cube_8.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Cube_9.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          geometry={nodes.Cube_10.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube_11.geometry}
          material={materials["Material.012"]}
        />
        <group
          position={[1.02, 0.288, 0.823]}
          rotation={[-1.738, 1.037, 0.198]}
          scale={[0.259, 0.239, 0.286]}
        >
          <mesh
            geometry={nodes.Circle001_1.geometry}
            material={materials.bumper}
          />
          <mesh
            geometry={nodes.Circle001_2.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          position={[0.128, 0.571, 0.455]}
          rotation={[Math.PI, 0, Math.PI]}
        >
          <mesh
            geometry={nodes.Cube002.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Cube002_1.geometry}
            material={materials.glass}
          />
        </group>
        <group position={[0.033, -0.58, 2.822]} rotation={[0.034, 0, 0]}>
          <mesh
            geometry={nodes.Cube005.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Cube005_1.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <mesh
          geometry={nodes.Cube008.geometry}
          material={materials.bumper}
          position={[0.04, 0.413, -1.797]}
          rotation={[0.348, -0.01, -0.003]}
        />
        <group position={[0.011, -0.204, 2.747]}>
          <mesh
            geometry={nodes.Cube010_1.geometry}
            material={materials["Material.007"]}
          />
          <mesh
            geometry={nodes.Cube010_2.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Cube010_3.geometry}
            material={materials["Material.006"]}
          />
        </group>
        <group
          position={[0.865, -0.016, 2.241]}
          rotation={[-0.034, 0.292, 0.01]}
        >
          <mesh
            geometry={nodes.Cube011_1.geometry}
            material={materials.Material}
          />
          <mesh
            geometry={nodes.Cube011_2.geometry}
            material={materials.headlamp}
          />
        </group>
        <group
          position={[0.776, -0.099, 2.391]}
          rotation={[-0.016, -0.062, 0.081]}
        >
          <mesh
            geometry={nodes.Cube014.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            geometry={nodes.Cube014_1.geometry}
            material={materials.smallhedlamp}
          />
        </group>
        <group
          position={[0.822, -0.088, 2.374]}
          rotation={[-0.016, -0.062, 0.081]}
        >
          <mesh
            geometry={nodes.Cube013.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            geometry={nodes.Cube013_1.geometry}
            material={materials.smallhedlamp}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/car/car.gltf");
