/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/saske/saske.gltf -t -r ./public 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
interface GLTFAction extends THREE.AnimationClip {
  name: string;
}
type GLTFResult = GLTF & {
  nodes: {};
  materials: {};
  animations: GLTFAction[];
};

export function Saske(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/saske/saske.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group />
    </group>
  );
}

useGLTF.preload("/saske/saske.gltf");
