/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/waterManholeCover/water_manhole_cover_4k.gltf -t -r ./public 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
interface GLTFAction extends THREE.AnimationClip {
  name: string;
}
type GLTFResult = GLTF & {
  nodes: {
    water_manhole_cover_frame: THREE.Mesh;
    water_manhole_cover: THREE.Mesh;
  };
  materials: {
    water_manhole_cover: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function WaterManholeCover(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/waterManholeCover/water_manhole_cover_4k.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.water_manhole_cover_frame.geometry}
        material={materials.water_manhole_cover}
      />
      <mesh
        geometry={nodes.water_manhole_cover.geometry}
        material={materials.water_manhole_cover}
      />
    </group>
  );
}

useGLTF.preload("/waterManholeCover/water_manhole_cover_4k.gltf");
